### ISSUE TITLE
Autorky and ratio doesn't work

### ISSUE THREAD

**Issue by maframan** [JonahKr/power-distribution-card#110]
Hi,
Autarky and Ratio remains to zero percentage value, 
We have configured: 
- Energy from grid
- Energy produced by solar
- House power consumed
Below the screenshot
![image](https://user-images.githubusercontent.com/24868793/178611791-72cdd6c6-bdbd-400a-afcd-bd0060d465a0.png)

Where I'm wronging?

**Comment by JonahKr** [comment]
Hey 👋 @maframan 
The issue is that you'll need to invert the home value.
Since the power is consumed by your home, a negative value is expected.
Just tick the box here for your home (Assorbimento casa) and you should be good to go.
![image](https://user-images.githubusercontent.com/38377070/178615103-f0ea03ec-231a-4055-b7f0-cbe17b04fca1.png)
You probably won't see anything though until your solar starts pushing power again.
I hope that solved it for you!

Take care and stay safe! 👍

**Comment by maframan** [comment]
Thanks a lot, now work very well!

![image](https://user-images.githubusercontent.com/24868793/178736889-21c45383-f8f2-41dd-90e7-65155500c932.png)
