### ISSUE TITLE
2022.11bx Entity picker not showing

### ISSUE THREAD

**Issue by Makin-Things** [JonahKr/power-distribution-card#115]
Hi,

With the 2022.11 beta's the entity pickers in the configuration screen has vanished.

![image](https://user-images.githubusercontent.com/91187456/198864283-b06fd14a-68e7-48a4-92cb-84cb27ca0678.png)

I am having a similar problem with a card I wrote (platinum-weather-card) but can't figure out how to fix it. Hoping you have some ideas.

**Comment by JonahKr** [comment]
Hey there 👋 
I sadly wasn't able to replicate the issue.
I ran the card in the latest `v2.5.4` and `Home Assistant 2022.11.0b3`.
Could you maybe share more details regarding your setup?
Thanks in advance and take care! 👍

**Comment by Makin-Things** [comment]
That is just creating a new card, nothing more. I think it will only show the problem if there are no cards in the panel that use an entity picker in their config. Try creating a new empty panel and then create a new pd card on that.

**Comment by JonahKr** [comment]
Ah ok i was able to replicate it thanks!
Usually this part here should have solved it so i am a bit unsure how it fails:
https://github.com/JonahKr/power-distribution-card/blob/3e9587c11177afd64b169bd21ad0c2bea7c2fa3b/src/editor.ts#L44-L55 

My guess right now would be that either the `customElements` are not available immediately so the load just doesn't happen or the loading of the editors has changed. I am going to check in with the frontend team and will update this issue once i get a response.

Take Care!

**Comment by Makin-Things** [comment]
This is where I was originally directed to get things loaded.
https://gist.github.com/thomasloven/5f965bd26e5f69876890886c09dd9ba8
Before the 2022.11 betas it works, but now line 39 returns undefined. It works for other elements, just not the ha-entity-picker.

**Comment by Stormhand** [comment]
Hello,
i just installed this card and have the same issue. There is no input field to enter the entity.

**Comment by JonahKr** [comment]
@Makin-Things I think i found the culprit!
I was just digging through the changes in the homeassistant frontend and found this:
https://github.com/home-assistant/frontend/commit/fe9967550bba7a9f9c5293b26383be0e2f9ac230
This means that all selector elements aren't loaded on editor load anymore but just when needed.
The workaround i found was to just go one abstraction higher by using `ha-selector` instead.

Old example:
```ts
<ha-entity-picker
          label="entity"
          .hass=${this.hass}
          .value=${item.entity}
          @value-changed=${this._itemChanged}
        ></ha-entity-picker>
```
New example:
```ts
<ha-selector
          label="entity"
          .hass=${this.hass}
          .selector=${{ entity: {} }}
          .value=${item.entity}
          @value-changed=${this._itemChanged}
        ></ha-selector>
```

Depending on your implementation of the `@value-changed` event handler, the event detail values now have to be preferred over the target value, since the later is not propagated from the entity-picker which is spawned within.


I am going to publish a new version with a fix tomorrow!

Thanks everyone and take care! 👍

**Comment by JonahKr** [comment]
OK an even easier fix is to just load the entities-card-editor since this one doesn't use the ha-form elements. (Maybe because of relying on the drag and drop functionality?)

**Comment by Makin-Things** [comment]
@JonahKr thanks for the info on how to fix things. I found I had to use a combination of both since none of the built in card editors use <ha-entity-attribute-picker> which I need. Bu I think I now have my card working again now.
