### ISSUE TITLE
Calculate home consumption automatically

### ISSUE THREAD

**Issue by bastelbert** [JonahKr/power-distribution-card#125]
Hi, first of all thanks for the great card!
I would be happy if the consumption of the (remaining) house electricity would be calculated automatically as a result of grid purchase, solar production and the consumption of e.g. a wallbox and the heat pump.
So one doesn't need to add "home" as an existing entity.
Like Loxone does in it's new energy flow monitor with the value "Rest":
<img width="363" alt="image" src="https://user-images.githubusercontent.com/32751381/212561219-1e7797df-3df3-4654-8ade-d176222e2357.png">

**Comment by JonahKr** [comment]
Hey there 👋 
Thanks for the suggestion.
I don't think this is the right approach though, since cards are not supposed to imply entity creation.
Also this would imply that there are no double entries and that production entries are complete.
This might work for your specific example but for many users, who add home appliances, and a total measurement, the calculation would just result in a wrong value. 
Therefore i would rather not include this feature. 

Additionally new Helper make it relatively easy to combine the states of multiple sensors in the UI: https://my.home-assistant.io/redirect/helpers/

Hope this is understandable.
Take care! 👍
