### ISSUE TITLE
Bars

### ISSUE THREAD

**Issue by Daverover66** [JonahKr/power-distribution-card#126]
Is it possible to have more than 2 bars in the centre. When I add a third bar, the card places it underneath the first 2 and it disappears off the bottom edge of the card.  Love this card by the way.

**Comment by JonahKr** [comment]
Hey there 👋 
The centre section of the card is just a little gimmick, and i am trying to include a proper card editor for next version... we'll se how that goes. That means that at the same time i don't think that cramming more bars into one row makes sense, especially not from a UI/ UX point of view.
Do you think it would be enough to just expand the card downwards instead of "cutting of" the remaining overflow?
Take care and stay safe!

**Comment by Daverover66** [comment]
Hiya 👋 
Yes, allowing the card to expand downwards would be a good solution. Only reason I asked about another bar in the middle is because I have more than one inverter and wanted to show a bar for each, but from a power flow perspective it might be more logical to have the inverter bars stacked vertically with any connected battery bar alongside the inverter to which it's connected. That would also allow for further expansion in the event a user connecting more batteries to each inverter 🤔. 
Thanks and best regards.

**Comment by Daverover66** [comment]
Brilliant! Thanks so much 🙏
