### ISSUE TITLE
Feature Request - separate battery charging/discharging entities

### ISSUE THREAD

**Issue by stellarsapience** [JonahKr/power-distribution-card#140]
Can currently only enter one entity for Battery preset. I use Envoy, which presents a charging and discharging power entity separately. Would like to see an option to enter both entities so the Battery preset will show arrows accordingly whether it is charging or discharging.

**Comment by JonahKr** [comment]
Hey there 👋 
Sorry that I  respond so late.
Since you have two entities, I think it would be easier to just create a template sensor which combines the two. (https://my.home-assistant.io/redirect/helpers/)
This should only take a minute and should be as simple as:
![grafik](https://github.com/JonahKr/power-distribution-card/assets/38377070/299c278c-1bc3-4c4a-a450-d384d10c6a3f)

I hope this helps!
If not, feel free to reopen the issue. 👍 
Take care and stay safe!
