### ISSUE TITLE
Wrong calc of AUTARKY related to battery charge

### ISSUE THREAD

**Issue by andrix988** [JonahKr/power-distribution-card#145]
I've considered "battery discharge" the energy/power incoming in the home.
I've considered "battery charge", usually done by PV, as minus, because this is energy/power from PV that will not reach directly the home.
In this way the AUTARKY calc consider the battery charge added to the power/energy to the grid, and not a reduced PV power/energy to the Home.

An alternative could be to exclude battery charge and discharge from the calc. But this alternative way is good only on the long period (i.e.: monthly) when charge/discharge are almost equal. But not on the daily energy or on the current power.

In the example picture the calc should be:
(81.6-29.9+29.6)/204.5= 40%

instead of:
(81.6+29.6)/(204.5+29.9)= 47%

![Screenshot_2023-05-20-10-50-59-275-edit_io homeassistant companion android](https://github.com/JonahKr/power-distribution-card/assets/128650876/545325d4-727b-42ed-9c53-7f772c455218)

**Comment by andrix988** [comment]
Just to add a full picture, my personal goal is to have in HA a symilar view to the one offered by the FusionSolar app (Huawei).
The green values are to calculate the RATIO (self consumption) as ratio between "energy absorbed by home from PV + Energy charged in the battery" / "total PV production"
The orange values are to calculate the AUTARKY as ratio between "energy coming directly from used by home + battery discharge" /  "total home consumption"

![IMG_20230520_112033](https://github.com/JonahKr/power-distribution-card/assets/128650876/41192170-4c4d-4c1c-8604-2135677d3062)
![Screenshot_2023-05-20-11-18-08-486-edit_io homeassistant companion android](https://github.com/JonahKr/power-distribution-card/assets/128650876/fec3b5c8-cc59-40b7-97e9-5d2b67e54b0b)

**Comment by JonahKr** [comment]
Hi 👋 ,
As per docs the layout and funktionality of this card stems from the Family of E3DC Energy Storage systems.
They interpret the battery charge as a portion of homeconsumption because the discharge of said batteries is normally only used to power home appliances. So it can be seen as a "power loan" in that sense. 
In your case what i would recommend is to just create your own custom autarky sensor in homeassistant using helpers (https://my.home-assistant.io/redirect/helpers/)
Afterwards just replace the bar in the middle with the entity of your custom sensor.

Apart from that it seems like your current sensor values don't make alot of sense considering the amounts (unless you have your own solar farm). Just to be sure: This card is meant for realtime consumption data in Watts. From a logic standpoint time data (kwh) should work aswell, but if you don't apply a rolling window the value of the resulting data might not be what you expect.

If you need some help with that feel free to reopen the issue, otherwise i highly recommend the Homeassistant discord.

Take care and stay safe! 👍
