### ISSUE TITLE
Autarky calculation

### ISSUE THREAD

**Issue by slipx06** [JonahKr/power-distribution-card#146]
Hi
I cant figure out how the card is calculating the autarky value shown below? I'm using presets for all of these so I assume the default consumer/producer tags would apply. Grid is excluded since it has no tag in the preset? Battery is a producer but value is negative so why is this not excluded as well? 

```
   this._config.entities.forEach((item, index) => {
      const value = this._val(item);

      if (!item.calc_excluded) {
        if (item.producer && value > 0) {
          production += value;
        }
        if (item.consumer && value < 0) {
          consumption -= value;
        }
      }
```

Autarky = production *100 /consumption = 8800/530 = 17%. 

![image](https://github.com/JonahKr/power-distribution-card/assets/7227275/b4aef8c8-0f21-47aa-a342-90193109ff97)

![image](https://github.com/JonahKr/power-distribution-card/assets/7227275/a1bcedbf-a137-4ae3-9934-c7c18446fe86)

Ratio = consumption *100/production = 34400/3687 = 9%

**Comment by JonahKr** [comment]
So your battery should work just fine.
I know what you mean now.
If you look here:
https://github.com/JonahKr/power-distribution-card/blob/1fc6a2fe8f3b5effe4b7336c78bddb37eb771758/src/presets.ts#L21-L26
You'll see that a battery is actually both a consumer and producer, since it can provide aswell as consume power.
In the calculations you can think of it as a e.g. car charger and additional solar panel in one entity, differentiated by the positive or negative value.

The formula you referenced works completely fine in that context.
If we have a consumer, consuming power (negative value), we add it to the total consumption. (total - - value == total + value)

**Comment by JonahKr** [comment]
@slipx06 I just saw your development on your custom card, keep up the good work!
If you need any help regarding this topic, feel free to message me.

**Comment by slipx06** [comment]
Thank you so much.
