### ISSUE TITLE
Hide ratio and autarky

### ISSUE THREAD

**Issue by TimOldenboom** [JonahKr/power-distribution-card#24]
First I have to say i LOVE your card 👍 .
It is not really an issue, more like an idea.
I want to use it for showing individual devices, like: house heating, fridge, computer and so on.
But i don't have any devices that produce energie (solar or wind) so i'm not so much interested in the ratio and autarky bars. Is it possible to make it optional to hide?
![image](https://user-images.githubusercontent.com/59979631/96089641-6f172280-0ec7-11eb-9415-970c19d52e62.png)

**Comment by JonahKr** [comment]
First of all, the Layout issue you are having -  i am working on it right now.
And regarding your suggestion: I have tried this actually before but didn't release it because it looked really ugly this way ... I am instead working on the option to add any card (Picture/Glace/Whatever) in the second column. When i am finished with this, i will just add a `none` option. 
Thanks for your suggestion 👍

**Comment by TimOldenboom** [comment]
Thanks for your reply.
I saw that the layout issue was already reported. 
That is even a better idea, to add a card! 
I will be patiently waiting for the release :)

**Comment by JonahKr** [comment]
https://github.com/JonahKr/power-distribution-card/releases/tag/v1.7

**Comment by JonahKr** [comment]
I would love to hear some feedback on this since this is my first time nesting lovelace cards. Did everything work for you? @TimOldenboom

**Comment by TimOldenboom** [comment]
It seems to work very well so far i have seen! I love it 👍 
With all the possibilities i have to decide what to do... 
But for now i have the total power consumed today and this week in the middle.
![image](https://user-images.githubusercontent.com/59979631/97728104-6f233f00-1ad1-11eb-98e1-ce5b4fada409.png)
