### ISSUE TITLE
kWh modifier introduced in 1.6.1 not working correctly

### ISSUE THREAD

**Issue by dannerph** [JonahKr/power-distribution-card#45]
Thanks for providing this very nice looking power distribution card. I am currently [integrating](https://github.com/dannerph/homeassistant-eon-energiemonitor) data from the EON Energiemonitor in order to visualize the regional energy generation/demand using your card. However I found a small bug:

https://github.com/JonahKr/power-distribution-card/blob/98781a7f02866ec39cb872e08c3899516a3b6930/src/power-distribution-card.ts#L109

```('kW' || 'kWh')``` is always ```'kW'```.
I would suggest to check for ```unit_of_measurement.startsWith('k')``` in order to be generic for all kinds of units. This might be extended with 'M' and 'G' later on.

**Comment by dannerph** [comment]
The data from the energiemonitor is in kWh, as it describes the cumulative power within a period of 15 minutes. I know that the power-distribution-card targets power, but as it also has the (broken) support for energy, I would be glade use it for my purpose ;)

**Comment by JonahKr** [comment]
Hey there 👋 @dannerph  ,
> However I found a small bug:

This piece was the result from here: https://github.com/JonahKr/power-distribution-card/issues/17 . initially i only supported kWh and Wh and so that was the quickest solution i came up with and, as you pointed out, definitely not the best 😉 .

> This might be extended with 'M' and 'G' later on.

I don't really see any usecase where someone would create such power without a reactor in his backyard but ofc by using it with different units this might actually be relevant.

The only reason its restricted at all, is the automatic calculations of the autarky/ratio(Eigenverbrauchsanteil). But considering that the card got more customizable, i need to rethink this whole concept.
I will implement these changes probably this evening if i have time and see if i need to implement additional checks for when units don't line up.

Thanks for your Issue 👍 

For the second Comment,  i am a bit curious how this works : is it just the cumulative power of the last 15minutes * 4 or kW(15min) ?

**Comment by dannerph** [comment]
Thanks for having a look on this issue!

A use case for bigger power/energy values might be if someone wants to visualize the energy import/export of a country, e.g. using data from ENTSO-E or the [electricity map](https://www.electricitymap.org/zone/DE). I do not know if this is already done, however it would be possible ;)

The EON Energiemonitor provides energy in kWh values for a certain 15 min period. Thus I am fine with visualising energy as kWh, however scaled correctly ;)

**Comment by JonahKr** [comment]
I think i fixed it now. I will work on one more thing for today and then release the patch. Thanks for the report 👍
