### ISSUE TITLE
It is working perfect, but a small bug in Visual Editor

### ISSUE THREAD

**Issue by pesor** [JonahKr/power-distribution-card#49]
@JonahKr 

It is working perfect: 👍 

Your card is PERFECT, and I would like to buy you a bear, but you do not have that possibility on your repo.

![Energy_overview](https://user-images.githubusercontent.com/3110308/104088801-bcf2bb00-5269-11eb-81b6-0a91f2410d56.JPG)
![Energy_overview-3](https://user-images.githubusercontent.com/3110308/104088816-d3991200-5269-11eb-9e9f-36ad98833667.JPG)

There is a little glitch in the Visual Editor though.

You set "absolut" value as default, but if you change it, you have to change it back and forth 3 times before you can save it.
If you do nothing, the "absolut" value is not changed, if you in a previously save has unmarked it.

Decimals points, do not work when setting the unit of Display, as you will see the value is 0,63, and not 631, it correct it self when save, but figure is shown without decimals.

As said minor flaws, and not important for the card usage.

![Energy_overview-1](https://user-images.githubusercontent.com/3110308/104088890-3f7b7a80-526a-11eb-95e4-b3587a604386.JPG)
![Energy_overview-2](https://user-images.githubusercontent.com/3110308/104088891-45715b80-526a-11eb-9f12-3478a878ffed.JPG)

**Comment by JonahKr** [comment]
Hey there 👋  @pesor 
Thanks for your kind words 😄 I added a BuyMeACoffee link to the Readme in the [dev](https://github.com/JonahKr/power-distribution-card/tree/dev) branch.

I was able to replicate your issue. For further Context: 
Normally the default values are set by a expression for something like this `item.display_abs || false` but since the default value is `true` every false value is overwritten with a `true` -> The checkbox is checked without the value being true.

Thanks alot for the Report 👍
