### ISSUE TITLE
Item Placeholder & Tap Action/Service

### ISSUE THREAD

**Issue by Stephan1908** [JonahKr/power-distribution-card#62]
Hello Jonah,

this is a very cool card.
I have two more questions:
Is it possible to execute an action, service, ... with tab_action or hold_action?
Is it possible to include a placeholder? For example, there should be producers on the left, two in my case, and consumers on the right, six in my case.

Greetings Stephan

**Comment by JonahKr** [comment]
Hey there @Stephan1908 👋 

Regarding the first one:
You mean a option to replace the current tab action? Atm the `more-info` event is triggered for the dialogue window to plop up.
If you want to, you can already replace the middle pane with 1 or multiple cards -> Button Cards which you can then use to trigger a script or smth.
I would prefer not to add additional logic for handling multi tabs/holds though.

Regarding your second question:
Not yet but I like the idea. Maybe I will make it so that if you remove the entity_id, it will be rendered as an empty item.

Take care and stay safe 👍 
Jonah

**Comment by Stephan1908** [comment]
Hi Jonah,
for the first one:
yes thats what i mean. the Problem is, when I tap on it, and the more-info dialogue opens, there is so many data, that the browser crashes. 

Greetings Stephan

**Comment by JonahKr** [comment]
In [v2,.3](https://github.com/JonahKr/power-distribution-card/releases/tag/v2.3) `tap_action` and `double_tap_action` got added as new settings. Additionally by removing the entity_id, you can now generate placeholders!

Thank you very much for your suggestion and Take care! 👍
