### ISSUE TITLE
Option to change icon and text size

### ISSUE THREAD

**Issue by Millennium-bug-82** [JonahKr/power-distribution-card#66]
I really like this card. It looks amazing.

The only thing I would like to see is an option to change the size of the text and icons.
Would this be possible?

**Comment by JonahKr** [comment]
Hey there @Millennium-bug-82 👋 ,

Since this is very specific in my opinion. The icon Sizes are the ones coming from the homeassistant icon element. I would rather not implement this in the current card but recommend you to checkout card-mod. https://github.com/thomasloven/lovelace-card-mod

This is made exactly for these small tweaks and allows you to change the CSS of Lovelace Cards.
The Dom Elements which you want to address are:
`icon > ha-icon` and
`badge > p` or `badge > .subtitle`
If you want, i could support you with that aswell.

Take care and stay safe! :+1:

Jonah
