### ISSUE TITLE
Change of arrow movement depending on negative/positive number

### ISSUE THREAD

**Issue by pesor** [JonahKr/power-distribution-card#81]
It would be really nice if it was possible to change the direction according to value, as is done for the color. 

At this moment the arrows follows the preset only. 

In this picture the arrows (grid) should point to the bars, when going to grid(green), and outside when taken from the grid(red). 

Right now they will always point outside. 

![0BA40E2B-6451-4D0C-8D2B-DE01403D969D](https://user-images.githubusercontent.com/3110308/132666890-190f90d9-189c-4301-99bb-2f5b5db1f25c.png)

**Comment by JonahKr** [comment]
Hey there @pesor 👋,
This is possible by using the [invert value](https://github.com/JonahKr/power-distribution-card#entity-configuration-%EF%B8%8F) option. 
It was removed from the UI editor some while ago because it was misinterpreted quite often.

If you think that this implementation isn't sufficient enough just reopen the issue and i will reconsider when i have more time.

Take Care and stay safe!

**Comment by pesor** [comment]
My fault, gone blind in settings. 

This works absolutely perfect.
