### ISSUE TITLE
Window to small for 3 bars

### ISSUE THREAD

**Issue by maxnomo60** [JonahKr/power-distribution-card#91]
hi, just tried to add a third bar in the middle of the window. But 3. bar appears below and then exceeds the whole window. How can i extend the Card-Window in this case ?  Or alternatively make bars fitting in one row ?

**Comment by JonahKr** [comment]
Hi there 👋,
Could you maybe send a screen shot or snipp of the card, so I could better understand what you mean? Thanks in advance 👍

**Comment by JonahKr** [comment]
I think I know what you mean: You mean by adding a third bar it gets moved underneath the two first ones. This is due to the width restrictions of the card itself. To sustain a reasonable amount of readability the size of the bar-containers is fixed.

Since this has been inactive for over a month,Ii will close this as stale. If you have some more information feel free to reopen the issue! 👍
